name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Настройка Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Сборка проекта
        run: mvn clean package -DskipTests

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Настройка Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Запуск тестов
        run: mvn test

  docker-build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Сборка Docker-образа
        run: docker build -t my-app .
      - name: Проверка успешности сборки
        run: docker images

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Деплой на Render
        run: |
          if [ "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" != "" ]; then
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
          else
            echo "Секрет RENDER_DEPLOY_HOOK_URL не настроен."
            exit 1
          fi

  healthcheck:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Ожидание прогрева сервера
        run: sleep 60
      - name: Проверка доступности API
        run: curl --fail https://librarymanagement-nxl6.onrender.com/api/authors || exit 1