name: CI/CD Pipeline Lab 8

on:
  push:
    branches: [ main, master ] # Срабатывает при пуше в ветки main или master

jobs:
  # ПУНКТ 5 ТЗ: Сборка и Тесты
  build-and-test:
    runs-on: ubuntu-latest

    services:
      # Поднимаем временную БД Postgres в контейнере, чтобы тесты Spring Boot прошли успешно
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: library_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: KopeYka
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Скачивание кода (Checkout)
        uses: actions/checkout@v4

      - name: Настройка Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Сборка проекта и прогон тестов
        # mvn clean package компилирует код и запускает тесты
        run: mvn clean package

  # ПУНКТ 5 ТЗ: Развертывание (Deploy)
  deploy:
    needs: build-and-test # Запустится только если сборка и тесты прошли без ошибок
    runs-on: ubuntu-latest
    steps:
      - name: Отправка вебхука деплоя на Render
        # Пингуем Render, чтобы он скачал новый код и обновил контейнер в облаке
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

  # ПУНКТ 5 ТЗ: Проверка работоспособности (Healthcheck)
  healthcheck:
    needs: deploy # Запустится строго после отправки команды на деплой
    runs-on: ubuntu-latest
    steps:
      - name: Ожидание запуска контейнера на хостинге (2 минуты)
        run: sleep 120

      - name: Проверка доступности эндпоинта (Healthcheck)
        # Стучимся на твой проверенный рабочий эндпоинт. Если возвращает 200 OK — шаг пройден!
        run: |
          curl --fail https://librarymanagement-nxl6.onrender.com/api/authors || exit 1