name: CI/CD Pipeline
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Настройка Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Сборка проекта
        run: mvn clean package -DskipTests

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Настройка Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Запуск тестов
        run: mvn test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Деплой на Render
        run: |
          if [ "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" != "" ]; then
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
          else
            echo "Секрет RENDER_DEPLOY_HOOK_URL пока не добавлен."
          fi

  healthcheck:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Проверка работоспособности
        run: curl --fail https://librarymanagement-nxl6.onrender.com/api/authors || exit 1